import, analyze & annotate disassembly
usandfriends/skullcode pull request #1
Opened 2017-07-16 02:03 UTC by kikaxa

2017-08-08 20:49 UTC, rgajrawala requested changes
Thanks for doing this. Let's just remove the first line and I'll merge. Planning on making this file a lot more easier to understand but this is a good start.

2017-08-08 20:49 UTC, usandfriends commented on disassembly.txt
> +﻿//disassembled by usandfriends
Haha I did not do this. Let's remove this for now.

2017-08-17 09:40 UTC, kikaxa commented
@usandfriends here you go.

2017-08-17 14:10 UTC, rgajrawala approved these changes

2017-08-17 14:10 UTC, merged